### PR TITLE
Alobugsdays - Aloception Logo

### LINKED ISSUE #257: Aloception Logo
The logo on the README is not up to date.

### PR DESCRIPTION
**Pull request by Ardorax**
Update the Aloception Logo.

* ***Fix #257*** : The Aloception logo wasn't up to date.

_____
This pull request includes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by thibo73800** [comment]
we need to assign Julie on this PR

**Review by thibo73800 — CHANGES_REQUESTED** [review]
Nope :)

**Review by Data-Iab — CHANGES_REQUESTED** [review]
We must add "-oss" and remove "for autonomous mobile robot"

**Review by Data-Iab — APPROVED** [review]

**Comment by Data-Iab** [comment]
@thibo73800 @anhtu293 @jsalotti

**Review by thibo73800 — APPROVED** [review]

**Pull request merged**
